# Generated by Django 5.0.4 on 2024-04-28 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_comment_postcategory_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_written',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
