# Generated by Django 5.0.4 on 2024-05-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_time_written'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_written',
        ),
    ]
