# Generated by Django 5.0.4 on 2024-05-18 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.subscription')),
            ],
        ),
    ]
